experiment:
  dataset: 
    dataset_name: cameraman
    dataset__img_size: [8]
  model:
    model_name: bimpcc.models.tvdenoising_model.TVDenoisingMPCC
    model_epsilon: 1e-3
    tol: 1e-4
    max_iter: 40 #iteraciones del mpcc total
    beta: 0.7
