experiment:
  dataset: 
    dataset_name: cameraman
    dataset__img_size: [8, 16, 32, 64, 128, 256]
  model:
    model_name: bimpcc.models.tvdenoising_model.TVDenoising
    model_reg_name: bimpcc.models.tvregularized.TVRegularized
    model_epsilon: 1e-3
    tol: 1e-4
    max_iter_reg: 3000
    max_iter: 300
    beta: 0.7
